// auth
export const RECEIVED_AUTH_STATUS = 'RECEIVED_AUTH_STATUS';

// projects
export const REQUESTED_PROJECTS = 'REQUESTED_PROJECTS';
export const RECEIVED_PROJECTS = 'RECEIVED_PROJECTS';
export const ERRORED_PROJECTS = 'ERRORED_PROJECTS';

// project
export const REQUESTED_SAVE_PROJECT = 'REQUESTED_SAVE_PROJECT';
export const RECEIVED_SAVE_PROJECT = 'RECEIVED_SAVE_PROJECT';
export const ERRORED_SAVE_PROJECT = 'ERRORED_SAVE_PROJECT';

export const REQUESTED_LOAD_PROJECT = 'REQUESTED_LOAD_PROJECT';
export const RECEIVED_LOAD_PROJECT = 'RECEIVED_LOAD_PROJECT';
export const ERRORED_LOAD_PROJECT = 'ERRORED_LOAD_PROJECT';

// editor
export const SET_APP = 'SET_APP';

export const RECEIVED_APP_VERSION = 'RECEIVED_APP_VERSION';
export const REQUESTED_APP_VERSION = 'REQUESTED_APP_VERSION';
export const ERRORED_APP_VERSION = 'ERRORED_APP_VERSION';

export const RECEIVED_SPREADSHEET_ID = 'RECEIVED_SPREADSHEET_ID';
export const RECEIVED_MODEL = 'RECEIVED_MODEL';
export const RECEIVED_IMPORT_ERROR = 'RECEIVED_IMPORT_ERROR';

export const SET_PRESENTER_AT_PATH = 'SET_PRESENTER_AT_PATH';
export const SET_EDITING_PRESENTER_PATH = 'SET_EDITING_PRESENTER_PATH';

export const APP_SAVING_INITIATED = 'APP_SAVING_INITIATED';
export const APP_SAVING_COMPLETED = 'APP_SAVING_COMPLETED';
export const APP_SAVING_FAILED = 'APP_SAVING_FAILED';

export const SET_PRESENTERS_BY_TYPE = 'SET_PRESENTERS_BY_TYPE'

export const SET_LINK_PATH = 'SET_LINK_PATH';
export const CLEAR_LINK_PATH = 'CLEAR_LINK_PATH';

// user app versions
export const REQUESTED_LOAD_USER_APP_VERSIONS = 'REQUESTED_LOAD_USER_APP_VERSIONS';
export const RECEIVED_LOAD_USER_APP_VERSIONS = 'RECEIVED_LOAD_USER_APP_VERSIONS';
export const ERRORED_LOAD_USER_APP_VERSIONS = 'ERRORED_LOAD_USER_APP_VERSIONS';
