export const RECEIVED_AUTH_STATUS = 'RECEIVED_AUTH_STATUS';

export const RECEIVED_SPREADSHEET_ID = 'RECEIVED_SPREADSHEET_ID';
export const RECEIVED_MODEL = 'RECEIVED_MODEL';
export const RECEIVED_IMPORT_ERROR = 'RECEIVED_IMPORT_ERROR';

export const SET_PRESENTER_AT_PATH = 'SET_PRESENTER_AT_PATH';
export const SET_EDITING_PRESENTER_PATH = 'SET_EDITING_PRESENTER_PATH';
