export const RECEIVED_AUTH_STATUS = 'RECEIVED_AUTH_STATUS';

export const RECEIVED_SPREADSHEET_ID = 'RECEIVED_SPREADSHEET_ID';
export const RECEIVED_MODEL = 'RECEIVED_MODEL';
export const RECEIVED_IMPORT_ERROR = 'RECEIVED_IMPORT_ERROR';
